# Generated by Django 2.2.6 on 2019-10-22 20:45

from django.db import migrations
import django.utils.timezone
import djongo.models.fields
import social_bmp_backend.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=djongo.models.fields.ArrayModelField(default=django.utils.timezone.now, model_container=social_bmp_backend.api.models.Comments, model_form_class=social_bmp_backend.api.models.CommentsForm),
            preserve_default=False,
        ),
    ]
