# Generated by Django 2.2.6 on 2019-11-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191113_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='All',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Angry',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Haha',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Like',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Love',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Sad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Wow',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='num_comments',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='num_shares',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_published',
            field=models.DateTimeField(max_length=20),
        ),
    ]
