# Generated by Django 2.2.6 on 2019-11-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191113_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='All',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Angry',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Haha',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Like',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Love',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Sad',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Wow',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_message',
            field=models.TextField(blank=True),
        ),
    ]
