# Generated by Django 2.2.6 on 2019-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191113_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
