# Generated by Django 2.2.6 on 2019-12-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191118_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=40, unique=True)),
                ('count', models.CharField(max_length=10)),
            ],
        ),
    ]
