# Generated by Django 2.2.6 on 2019-12-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
